"""Generate reports/data_dictionary.md from the actual data.

Descriptions are curated here; types, null counts, cardinality and examples are
read from the files themselves, so the dictionary cannot drift out of date the
way a hand-written one does.

Run from the project root::

    python -m src.data.data_dictionary
"""

from __future__ import annotations

import sqlite3
import sys

import pandas as pd

from src.data.schema import LABEL_NAMES, SPLITS
from src.utils.paths import DB_PATH, PROCESSED_DIR, REPORTS_DIR

DESCRIPTIONS = {
    "id": "Stable primary key, `<split>_<6-digit index>`. Used to join predictions and logs back to a message.",
    "split": "Which official partition the row belongs to: train, validation or test.",
    "text": "Original message, unmodified. Use this for transformer models, which have their own tokenizer.",
    "text_clean": "Lowercased, URL/mention-stripped, punctuation-free version. Use this for TF-IDF and other bag-of-words features.",
    "label": "Emotion as integer 0-5. Encoding is fixed by `src/data/schema.py` and must not be re-derived.",
    "label_name": "Human-readable emotion name, redundant with `label` but kept for readable reports.",
    "n_words": "Whitespace-delimited token count of the ORIGINAL text.",
    "n_chars": "Character count of the ORIGINAL text.",
    "has_negation": "1 if the cleaned text contains a negation token, else 0. Provided as an error-analysis slice.",
}

TABLE_NOTES = {
    "emotions": "Lookup table. Foreign key target for every label column, so an invalid label cannot be inserted.",
    "messages": "The dataset itself, all three splits in one table, distinguished by `split`.",
    "models": "Model registry. Every trained model is registered here before its predictions are stored.",
    "predictions": "One row per (message, model). `UNIQUE(message_id, model_id)` prevents double-counting after a re-run.",
    "topics": "Topic definitions produced by the topic-modelling step.",
    "message_topics": "Junction table: a message may carry several topics with different weights.",
    "inference_logs": "One row per inference call from the Streamlit app or a batch job. Feeds the monitoring queries.",
}


def main() -> int:
    frames = {}
    for split in SPLITS:
        path = PROCESSED_DIR / f"{split}.csv"
        if not path.exists():
            print(f"{path} not found. Run `python -m src.data.build` first.")
            return 1
        frames[split] = pd.read_csv(path, encoding="utf-8")

    train = frames["train"]
    lines = [
        "# Data Dictionary",
        "",
        "Generated by `python -m src.data.data_dictionary`. Do not edit by hand.",
        "",
        "## 1. Source",
        "",
        "| field | value |",
        "|---|---|",
        "| Dataset | `dair-ai/emotion` (Hugging Face) |",
        "| Configuration | `split` |",
        "| Domain | English social-media messages |",
        "| Task | Single-label multi-class classification, 6 classes |",
        "| Licence | Educational and research use only |",
        "| Citation | Saravia et al., *CARER: Contextualized Affect Representations for Emotion Recognition*, EMNLP 2018 |",
        "",
        "## 2. Label encoding",
        "",
        "This mapping is fixed. Re-deriving it anywhere else will silently corrupt "
        "every confusion matrix in the project.",
        "",
        "| id | name |",
        "|---|---|",
    ]
    lines += [f"| {i} | {name} |" for i, name in enumerate(LABEL_NAMES)]

    lines += [
        "",
        "## 3. Processed files",
        "",
        "Location: `data/processed/<split>.csv`, UTF-8 encoded.",
        "",
        "| split | rows |",
        "|---|---|",
    ]
    lines += [f"| {s} | {len(df):,} |" for s, df in frames.items()]

    lines += [
        "",
        "## 4. Columns",
        "",
        "| column | type | nulls | distinct | example | description |",
        "|---|---|---|---|---|---|",
    ]
    for col in train.columns:
        series = train[col]
        example = str(series.dropna().iloc[0])
        if len(example) > 42:
            example = example[:42] + "..."
        example = example.replace("|", "\\|")
        lines.append(
            f"| `{col}` | {series.dtype} | {int(series.isna().sum())} | "
            f"{series.nunique():,} | {example} | {DESCRIPTIONS.get(col, '')} |"
        )

    # numeric ranges
    lines += [
        "",
        "### Numeric ranges (train)",
        "",
        "| column | min | median | mean | p95 | max |",
        "|---|---|---|---|---|---|",
    ]
    for col in ["n_words", "n_chars"]:
        s = train[col]
        lines.append(
            f"| `{col}` | {s.min()} | {s.median():.0f} | {s.mean():.1f} | "
            f"{s.quantile(0.95):.0f} | {s.max()} |"
        )

    # database schema
    if DB_PATH.exists():
        lines += ["", "## 5. Database schema", "",
                  f"SQLite file at `{DB_PATH.name}`, built by `python -m src.data.load_sql`.", ""]
        conn = sqlite3.connect(DB_PATH)
        try:
            tables = [
                r[0] for r in conn.execute(
                    "SELECT name FROM sqlite_master WHERE type='table' "
                    "AND name NOT LIKE 'sqlite_%' ORDER BY name"
                )
            ]
            for table in tables:
                (count,) = conn.execute(f"SELECT COUNT(*) FROM {table}").fetchone()
                lines += [
                    f"### `{table}` ({count:,} rows)", "",
                    TABLE_NOTES.get(table, ""), "",
                    "| column | type | not null | pk |", "|---|---|---|---|",
                ]
                for _, name, ctype, notnull, _, pk in conn.execute(
                    f"PRAGMA table_info({table})"
                ):
                    lines.append(
                        f"| `{name}` | {ctype} | {'yes' if notnull else ''} | "
                        f"{'yes' if pk else ''} |"
                    )
                lines.append("")
        finally:
            conn.close()
    else:
        lines += ["", "## 5. Database schema", "",
                  "_Not generated - run `python -m src.data.load_sql` first._", ""]

    lines += [
        "## 6. Known limitations",
        "",
        "- Short English social-media text only; performance on long-form or "
        "non-English customer messages is unknown and untested.",
        "- Six emotions is a coarse taxonomy. Real support messages carry mixed "
        "or absent emotion, which this label set cannot express.",
        "- Labels are crowd-derived, not clinical. They must not be presented as "
        "mental-health assessments.",
        "- Near-duplicate messages were removed; heavily paraphrased duplicates "
        "may remain.",
        "",
    ]

    path = REPORTS_DIR / "data_dictionary.md"
    path.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote reports/{path.name} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
